### ISSUE TITLE
ERROR: for kubelet  linux mounts: Path /var/lib/kubelet is mounted on / but it is not a shared mount.

### ISSUE THREAD

**Issue by josephwinston** [weaveworks/kubernetes-anywhere#88]
Just starting on Ubuntu 16.04 LTS with Docker 1.11.1 and I'm receiving the message:

```bash
ERROR: for kubelet  linux mounts: Path /var/lib/kubelet is mounted on / but it is not a shared mount.
```
What can I provide/help with to chase down and squash this?

**Comment by josephwinston** [comment]
Fixed with <https://github.com/weaveworks/kubernetes-anywhere/blob/master/FIXES.md>

**Comment by sjezewski** [comment]
I'm having the same issue and that link no longer works. Any clues to what you did to fix the problem?

**Comment by colemickens** [comment]
Basically everything in the project has changed since July/August and this *theoretically* shouldn't be an issue anymore. Can you please provide additional details about how you're running this?

* Have you updated your checkout?
* Are you running against GCE or Azure?
* Where are you receiving this message? On all nodes, just the master?

Additionally, it would be helpful if you can provide your `.config.json` file from the root of your checkout (you should redact any passwords or secrets in it).

**Comment by gshiva** [comment]
Not using this project, but running into the same error with Ubuntu 16.0.4 LTS and Docker 1.11.X.

Using https://github.com/vyshane/kid

**Comment by colemickens** [comment]
I can't provide support for that project and that issue was not occurring in this project while I was working on it.

If I might suggest anything it would be to look at the mount propagation flags for docker. For example, we reset them to be shared: https://github.com/kubernetes/kubernetes-anywhere/blob/master/phase1/azure/configure-vm.sh#L9

**Comment by gabrielgrant** [comment]
I was also getting `docker: Error response from daemon: linux mounts: Path /var/lib/kubelet is mounted on / but it is not a shared mount..` when trying to launch k8s locally. bind-mounting that dir and making it shared seemed to fix the problem:

```
sudo mount -o bind /var/lib/kubelet /var/lib/kubelet
sudo mount --make-shared /var/lib/kubelet
```
